/*
 * Copyright (c) 2016 Phạm Minh Hoàng
 * Email:		hoangpham61691@gmail.com
 * Framework:	MyClasses
 * Description:	This script is generated by MyUGUIConfigIDEditorWindow
 */

namespace MyClasses.UI
{
	public enum EUnitySceneID
	{
		MainUnityScene = 0,
	}

	public enum ESceneID
	{
		MainScene = 0,
		GroupScene = 1,
		GameScene = 2,
	}

	public enum ESubSceneID
	{
		GroupASubScene = 0,
		GroupBSubScene = 1,
		GroupCSubScene = 2,
		GroupDSubScene = 3,
		GroupESubScene = 4,
	}

	public enum EPopupID
	{
		Dialog0ButtonPopup = 0,
		Dialog1ButtonPopup = 1,
		Dialog2ButtonsPopup = 2,
		PoolPopup = 3,
		LocalizationPopup = 4,
		AdMobPopup = 5,
		ReusableListViewPopup = 6,
		ReusableListViewPopup2 = 7,
		ExtensionPopup = 8,
		ForbiddenTextPopup = 9,
		ScrollSnapPopup = 10,
	}

	public enum EToastNotificationID
	{
		TopCenterToastNotification = 0,
	}
}