/*
 * Copyright (c) 2016 Phạm Minh Hoàng
 * Email:		hoangpham61691@gmail.com
 * Framework:	MyClasses
 * Description:	This script is generated by MyUGUIConfigIDEditorWindow
 */

namespace MyClasses.UI
{
	public enum EUnitySceneID
	{
		MainUnityScene,
	}

	public enum ESceneID
	{
		MainScene,
		GroupScene,
		GameScene,
	}

	public enum ESubSceneID
	{
		GroupASubScene,
		GroupBSubScene,
		GroupCSubScene,
		GroupDSubScene,
		GroupESubScene,
	}

	public enum EPopupID
	{
		Dialog0ButtonPopup,
		Dialog1ButtonPopup,
		Dialog2ButtonsPopup,
		PoolPopup,
		LocalizationPopup,
		AdMobPopup,
		ReusableListViewPopup,
		ReusableListViewPopup2,
		ExtensionPopup,
		ForbiddenTextPopup,
	}

	public enum EToastNotificationID
	{
		TopCenterToastNotification,
	}
}